# Generated by Django 5.1 on 2024-08-26 10:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название курса')),
                ('description', models.TextField(verbose_name='Описание курса')),
                ('imagery', models.ImageField(blank=True, null=True, upload_to='materials/', verbose_name='Изображение(превью)')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Учебный курс',
                'verbose_name_plural': 'Учебные курсы',
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название темы курса')),
                ('description', models.TextField(verbose_name='Описание темы')),
                ('imagery', models.ImageField(blank=True, null=True, upload_to='materials/', verbose_name='Изображение(превью)')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.course', verbose_name='Учебный курс')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Тема курса',
                'verbose_name_plural': 'Темы курса',
            },
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название лекции к теме')),
                ('description', models.TextField(verbose_name='Описание лекции')),
                ('imagery', models.ImageField(blank=True, null=True, upload_to='materials/', verbose_name='Изображение(превью)')),
                ('content', models.FileField(blank=True, null=True, upload_to='materials/', verbose_name='Содержание лекции')),
                ('video', models.URLField(blank=True, max_length=150, null=True, verbose_name='Ссылка на видео')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.topic', verbose_name='Тема')),
            ],
            options={
                'verbose_name': 'Лекция',
                'verbose_name_plural': 'Лекции',
            },
        ),
    ]
