# Generated by Django 5.1 on 2024-08-29 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0002_rename_tests_test_rename_questions_question_answer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='is_correct',
            field=models.BooleanField(default=False, verbose_name='Правильный ответ'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Вопрос'),
        ),
    ]
